id: PYSEC-0000-CVE-2021-42343
details: An issue was discovered in Dask (aka python-dask) through 2021.09.1. Single
  machine Dask clusters started with dask.distributed.LocalCluster or dask.distributed.Client
  (which defaults to using LocalCluster) would mistakenly configure their respective
  Dask workers to listen on external interfaces (typically with a randomly selected
  high port) rather than only on localhost. A Dask cluster created using this method
  (when running on a machine that has an applicable port exposed) could be used by
  a sophisticated attacker to achieve remote code execution.
affected:
- package:
    name: dask
    ecosystem: PyPI
    purl: pkg:pypi:dask
  ranges:
  - type: ECOSYSTEM
    events:
    events:
      - introduced: "0"
      - fixed: 2021.10.0
references:
- type: WEB
  url: https://docs.dask.org/en/latest/changelog.html
- type: WEB
  url: https://github.com/dask/dask/tags
aliases:
- CVE-2021-42343
modified: "2021-11-04T03:15:00Z"
published: "2021-10-26T11:15:00Z"
