id: PYSEC-0000-CVE-2016-2513
package:
  name: django
  ecosystem: PyPI
details: The password hasher in contrib/auth/hashers.py in Django before 1.8.10 and
  1.9.x before 1.9.3 allows remote attackers to enumerate users via a timing attack
  involving login requests.
affects:
  ranges:
  - type: GIT
    repo: https://github.com/django/django
    fixed: 67b46ba7016da2d259c1ecc7d666d11f5e1cfaab
  - type: ECOSYSTEM
    fixed: 1.8.10
  - type: ECOSYSTEM
    introduced: '1.9'
    fixed: 1.9.3
references:
- type: WEB
  url: https://www.djangoproject.com/weblog/2016/mar/01/security-releases/
- type: WEB
  url: https://github.com/django/django/commit/67b46ba7016da2d259c1ecc7d666d11f5e1cfaab
- type: WEB
  url: http://rhn.redhat.com/errata/RHSA-2016-0504.html
- type: WEB
  url: http://www.oracle.com/technetwork/topics/security/bulletinapr2016-2952098.html
- type: WEB
  url: http://www.securityfocus.com/bid/83878
- type: WEB
  url: http://www.ubuntu.com/usn/USN-2915-2
- type: WEB
  url: http://www.ubuntu.com/usn/USN-2915-3
- type: WEB
  url: http://www.debian.org/security/2016/dsa-3544
- type: WEB
  url: http://rhn.redhat.com/errata/RHSA-2016-0502.html
- type: WEB
  url: http://rhn.redhat.com/errata/RHSA-2016-0505.html
- type: WEB
  url: http://rhn.redhat.com/errata/RHSA-2016-0506.html
- type: WEB
  url: http://www.ubuntu.com/usn/USN-2915-1
- type: WEB
  url: http://www.securitytracker.com/id/1035152
aliases:
- CVE-2016-2513
modified: "2017-09-08T01:29:00Z"
published: "2016-04-08T15:59:00Z"
