id: PYSEC-0000-CVE-2014-3730
package:
  name: django
  ecosystem: PyPI
details: The django.util.http.is_safe_url function in Django 1.4 before 1.4.13, 1.5
  before 1.5.8, 1.6 before 1.6.5, and 1.7 before 1.7b4 does not properly validate
  URLs, which allows remote attackers to conduct open redirect attacks via a malformed
  URL, as demonstrated by "http:\\\djangoproject.com."
affects:
  ranges:
  - type: ECOSYSTEM
    introduced: "1.4"
    fixed: 1.4.13
  - type: ECOSYSTEM
    introduced: "1.5"
    fixed: 1.5.8
  - type: ECOSYSTEM
    introduced: "1.6"
    fixed: 1.6.5
  - type: ECOSYSTEM
    introduced: "1.7"
    fixed: 1.7b4
references:
- type: WEB
  url: http://ubuntu.com/usn/usn-2212-1
- type: WEB
  url: https://www.djangoproject.com/weblog/2014/may/14/security-releases-issued/
- type: WEB
  url: http://www.openwall.com/lists/oss-security/2014/05/15/3
- type: WEB
  url: http://www.openwall.com/lists/oss-security/2014/05/14/10
- type: WEB
  url: http://www.debian.org/security/2014/dsa-2934
- type: WEB
  url: http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html
- type: WEB
  url: http://www.securityfocus.com/bid/67410
- type: WEB
  url: http://secunia.com/advisories/61281
aliases:
- CVE-2014-3730
modified: "2018-10-30T16:27:00Z"
published: "2014-05-16T15:55:00Z"
