id: PYSEC-2022-213
details: An issue was discovered in Django 3.2 before 3.2.14 and 4.0 before 4.0.6.
  The Trunc() and Extract() database functions are subject to SQL injection if untrusted
  data is used as a kind/lookup_name value. Applications that constrain the lookup
  name and kind choice to a known safe list are unaffected.
affected:
- package:
    name: django
    ecosystem: PyPI
    purl: pkg:pypi/django
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "3.2"
    - fixed: 3.2.14
    - introduced: "4.0"
    - fixed: 4.0.6
  versions:
  - "3.2"
  - 3.2.1
  - 3.2.10
  - 3.2.11
  - 3.2.12
  - 3.2.13
  - 3.2.2
  - 3.2.3
  - 3.2.4
  - 3.2.5
  - 3.2.6
  - 3.2.7
  - 3.2.8
  - 3.2.9
  - "4.0"
  - 4.0.1
  - 4.0.2
  - 4.0.3
  - 4.0.4
  - 4.0.5
references:
- type: ARTICLE
  url: https://www.djangoproject.com/weblog/2022/jul/04/security-releases/
- type: WEB
  url: https://docs.djangoproject.com/en/4.0/releases/security/
- type: WEB
  url: https://groups.google.com/forum/#!forum/django-announce
- type: ADVISORY
  url: https://github.com/advisories/GHSA-p64x-8rxx-wf6q
aliases:
- CVE-2022-34265
- GHSA-p64x-8rxx-wf6q
modified: "2022-07-04T18:45:03.823587Z"
published: "2022-07-04T16:15:00Z"
