id: PYSEC-0000-CVE-2019-16224
details: 'An issue was discovered in py-lmdb 0.97. For certain values of md_flags,
  mdb_node_add does not properly set up a memcpy destination, leading to an invalid
  write operation. NOTE: this outcome occurs when accessing a data.mdb file supplied
  by an attacker.'
affected:
- package:
    name: lmdb
    ecosystem: PyPI
    purl: pkg:pypi:lmdb
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: "0.98"
references:
- type: WEB
  url: https://github.com/TeamSeri0us/pocs/tree/master/lmdb/lmdb%20initialization%20vuln
- type: PACKAGE
  url: https://pypi.org/project/lmdb
- type: ADVISORY
  url: https://nvd.nist.gov/vuln/detail/CVE-2019-16224
aliases:
- CVE-2019-16224
modified: "2020-09-14T15:20:00Z"
published: "2019-09-11T15:15:00Z"
