affected:
- package:
    ecosystem: PyPI
    name: tensorflow-cpu
    purl: pkg:pypi:tensorflow-cpu
  ranges:
  - events:
    - introduced: '0'
    - fixed: 27b417360cbd671ef55915e4bb6bb06af8b8a832
    - fixed: ca8c013b5e97b1373b3bb1c97ea655e69f31a575
    repo: https://github.com/tensorflow/tensorflow
    type: GIT
  - events:
    - introduced: '0'
    - fixed: 1.15.4
    - introduced: 2.0.0
    - fixed: 2.0.3
    - introduced: 2.1.0
    - fixed: 2.1.2
    - introduced: 2.2.0
    - fixed: 2.2.1
    - introduced: 2.3.0
    - fixed: 2.3.1
    type: ECOSYSTEM
aliases:
- CVE-2020-15202
- GHSA-h6fg-mjxg-hqq4
details: In Tensorflow before versions 1.15.4, 2.0.3, 2.1.2, 2.2.1 and 2.3.1, the
  `Shard` API in TensorFlow expects the last argument to be a function taking two
  `int64` (i.e., `long long`) arguments. However, there are several places in TensorFlow
  where a lambda taking `int` or `int32` arguments is being used. In these cases,
  if the amount of work to be parallelized is large enough, integer truncation occurs.
  Depending on how the two arguments of the lambda are used, this can result in segfaults,
  read/write outside of heap allocated arrays, stack overflows, or data corruption.
  The issue is patched in commits 27b417360cbd671ef55915e4bb6bb06af8b8a832 and ca8c013b5e97b1373b3bb1c97ea655e69f31a575,
  and is released in TensorFlow versions 1.15.4, 2.0.3, 2.1.2, 2.2.1, or 2.3.1.
id: PYSEC-0000-CVE-2020-15202
modified: '2020-10-29T16:15:00Z'
published: '2020-09-25T19:15:00Z'
references:
- type: FIX
  url: https://github.com/tensorflow/tensorflow/commit/27b417360cbd671ef55915e4bb6bb06af8b8a832
- type: ADVISORY
  url: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-h6fg-mjxg-hqq4
- type: WEB
  url: https://github.com/tensorflow/tensorflow/releases/tag/v2.3.1
- type: FIX
  url: https://github.com/tensorflow/tensorflow/commit/ca8c013b5e97b1373b3bb1c97ea655e69f31a575
- type: WEB
  url: http://lists.opensuse.org/opensuse-security-announce/2020-10/msg00065.html
