id: PYSEC-0000-CVE-2022-21732
details: Tensorflow is an Open Source Machine Learning Framework. The implementation
  of `ThreadPoolHandle` can be used to trigger a denial of service attack by allocating
  too much memory. This is because the `num_threads` argument is only checked to not
  be negative, but there is no upper bound on its value. The fix will be included
  in TensorFlow 2.8.0. We will also cherrypick this commit on TensorFlow 2.7.1, TensorFlow
  2.6.3, and TensorFlow 2.5.3, as these are also affected and still in supported range.
affected:
- package:
    name: tensorflow-cpu
    ecosystem: PyPI
    purl: pkg:pypi/tensorflow-cpu
  ranges:
  - type: GIT
    repo: https://github.com/tensorflow/tensorflow
    events:
    - introduced: "0"
    - fixed: e3749a6d5d1e8d11806d4a2e9cc3123d1a90b75e
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 2.5.3
    - introduced: 2.6.0
    - fixed: 2.6.3
references:
- type: FIX
  url: https://github.com/tensorflow/tensorflow/commit/e3749a6d5d1e8d11806d4a2e9cc3123d1a90b75e
- type: ADVISORY
  url: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-c582-c96p-r5cq
- type: WEB
  url: https://github.com/tensorflow/tensorflow/blob/5100e359aef5c8021f2e71c7b986420b85ce7b3d/tensorflow/core/kernels/data/experimental/threadpool_dataset_op.cc#L79-L135
aliases:
- CVE-2022-21732
- GHSA-c582-c96p-r5cq
modified: "2022-02-09T03:08:00Z"
published: "2022-02-03T12:15:00Z"
