id: PYSEC-0000-CVE-2017-8359
details: Google gRPC before 2017-03-29 has an out-of-bounds write caused by a heap-based
  use-after-free related to the grpc_call_destroy function in core/lib/surface/call.c.
affected:
- package:
    name: grpcio
    ecosystem: PyPI
    purl: pkg:pypi:grpcio
  ranges:
  - type: GIT
    repo: https://github.com/grpc/grpc
    events:
    - introduced: "0"
    - fixed: 6544a2d5d9ecdb64214da1d228886a7d15bbf5c7
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 1.3.0
references:
- type: WEB
  url: https://github.com/grpc/grpc/pull/10353
- type: FIX
  url: https://github.com/grpc/grpc/commit/6544a2d5d9ecdb64214da1d228886a7d15bbf5c7
- type: WEB
  url: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=726
- type: WEB
  url: http://www.securityfocus.com/bid/98280
- type: PACKAGE
  url: https://pypi.org/project/grpcio
- type: ADVISORY
  url: https://nvd.nist.gov/vuln/detail/CVE-2017-8359
aliases:
- CVE-2017-8359
modified: "2017-12-12T17:05:00Z"
published: "2017-04-30T17:59:00Z"
