id: PYSEC-0000-CVE-2013-4189
package:
  name: plone
  ecosystem: PyPI
details: Multiple unspecified vulnerabilities in (1) dataitems.py, (2) get.py, and
  (3) traverseName.py in Plone 2.1 through 4.1, 4.2.x through 4.2.5, and 4.3.x through
  4.3.1 allow remote authenticated users with administrator access to a subtree to
  access nodes above the subtree via unknown vectors.
affects:
  ranges:
  - type: ECOSYSTEM
    introduced: "2.1"
    fixed: 4.1.1
  - type: ECOSYSTEM
    introduced: "4.2"
    fixed: 4.2.6
  - type: ECOSYSTEM
    introduced: "4.3"
    fixed: 4.3.2
references:
- type: WEB
  url: http://seclists.org/oss-sec/2013/q3/261
- type: WEB
  url: http://plone.org/products/plone/security/advisories/20130618-announcement
- type: WEB
  url: http://plone.org/products/plone-hotfix/releases/20130618
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=978450
aliases:
- CVE-2013-4189
modified: "2014-03-12T01:02:00Z"
published: "2014-03-11T19:37:00Z"
