id: PYSEC-2019-200
details: python-requests-Kerberos through 0.5 does not handle mutual authentication
affected:
- package:
    name: requests-kerberos
    ecosystem: PyPI
    purl: pkg:pypi:requests-kerberos
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: "0.6"
  versions:
  - 0.0.0
  - "0.2"
  - "0.3"
  - "0.4"
  - "0.5"
references:
- type: REPORT
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2014-8650
- type: WEB
  url: http://www.openwall.com/lists/oss-security/2014/11/07/1
- type: WEB
  url: https://security-tracker.debian.org/tracker/CVE-2014-8650
- type: WEB
  url: http://www.securityfocus.com/bid/70909
aliases:
- CVE-2014-8650
modified: "2021-08-27T03:22:19.338890Z"
published: "2019-12-15T22:15:00Z"
