id: PYSEC-0000-CVE-2022-23564
details: Tensorflow is an Open Source Machine Learning Framework. When decoding a
  resource handle tensor from protobuf, a TensorFlow process can encounter cases where
  a `CHECK` assertion is invalidated based on user controlled arguments. This allows
  attackers to cause denial of services in TensorFlow processes. The fix will be included
  in TensorFlow 2.8.0. We will also cherrypick this commit on TensorFlow 2.7.1, TensorFlow
  2.6.3, and TensorFlow 2.5.3, as these are also affected and still in supported range.
affected:
- package:
    name: tensorflow-gpu
    ecosystem: PyPI
    purl: pkg:pypi/tensorflow-gpu
  ranges:
  - type: GIT
    repo: https://github.com/tensorflow/tensorflow
    events:
    - introduced: "0"
    - fixed: 14fea662350e7c26eb5fe1be2ac31704e5682ee6
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 2.5.3
    - introduced: 2.6.0
    - fixed: 2.6.3
references:
- type: FIX
  url: https://github.com/tensorflow/tensorflow/commit/14fea662350e7c26eb5fe1be2ac31704e5682ee6
- type: ADVISORY
  url: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-8rcj-c8pj-v3m3
aliases:
- CVE-2022-23564
- GHSA-8rcj-c8pj-v3m3
modified: "2022-02-09T17:49:00Z"
published: "2022-02-04T23:15:00Z"
