affected:
- package:
    ecosystem: PyPI
    name: tensorflow-gpu
    purl: pkg:pypi:tensorflow-gpu
  ranges:
  - events:
    - introduced: '0'
    - fixed: 82e6203221865de4008445b13c69b6826d2b28d9
    repo: https://github.com/tensorflow/tensorflow
    type: GIT
  - events:
    - introduced: '0'
    - fixed: 2.1.4
    - introduced: 2.2.0
    - fixed: 2.2.3
    - introduced: 2.3.0
    - fixed: 2.3.3
    - introduced: 2.4.0
    - fixed: 2.4.2
    type: ECOSYSTEM
aliases:
- CVE-2021-29619
- GHSA-wvjw-p9f5-vq28
details: TensorFlow is an end-to-end open source platform for machine learning. Passing
  invalid arguments (e.g., discovered via fuzzing) to `tf.raw_ops.SparseCountSparseOutput`
  results in segfault. The fix will be included in TensorFlow 2.5.0. We will also
  cherrypick this commit on TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and
  TensorFlow 2.1.4, as these are also affected and still in supported range.
id: PYSEC-0000-CVE-2021-29619
modified: '2021-08-27T03:22:42.523296Z'
published: '2021-05-14T20:15:00Z'
references:
- type: FIX
  url: https://github.com/tensorflow/tensorflow/commit/82e6203221865de4008445b13c69b6826d2b28d9
- type: ADVISORY
  url: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-wvjw-p9f5-vq28
