id: PYSEC-0000-CVE-2022-23569
details: Tensorflow is an Open Source Machine Learning Framework. Multiple operations
  in TensorFlow can be used to trigger a denial of service via `CHECK`-fails (i.e.,
  assertion failures). This is similar to TFSA-2021-198 and has similar fixes. We
  have patched the reported issues in multiple GitHub commits. It is possible that
  other similar instances exist in TensorFlow, we will issue fixes as these are discovered.
  The fix will be included in TensorFlow 2.8.0. We will also cherrypick this commit
  on TensorFlow 2.7.1, TensorFlow 2.6.3, and TensorFlow 2.5.3, as these are also affected
  and still in supported range.
affected:
- package:
    name: tensorflow-gpu
    ecosystem: PyPI
    purl: pkg:pypi/tensorflow-gpu
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 2.5.3
    - introduced: 2.6.0
    - fixed: 2.6.3
references:
- type: ADVISORY
  url: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-qj5r-f9mv-rffh
- type: ADVISORY
  url: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/security/advisory/tfsa-2021-198.md
aliases:
- CVE-2022-23569
- GHSA-qj5r-f9mv-rffh
modified: "2022-02-09T05:03:00Z"
published: "2022-02-03T13:15:00Z"
