id: PYSEC-0000-CVE-2021-41200
details: TensorFlow is an open source platform for machine learning. In affected versions
  if `tf.summary.create_file_writer` is called with non-scalar arguments code crashes
  due to a `CHECK`-fail. The fix will be included in TensorFlow 2.7.0. We will also
  cherrypick this commit on TensorFlow 2.6.1, TensorFlow 2.5.2, and TensorFlow 2.4.4,
  as these are also affected and still in supported range.
affected:
- package:
    name: tensorflow
    ecosystem: PyPI
    purl: pkg:pypi:tensorflow
  ranges:
  - type: GIT
    repo: https://github.com/tensorflow/tensorflow
    events:
    - introduced: "0"
    - fixed: 874bda09e6702cd50bac90b453b50bcc65b2769e
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 2.4.4
    - introduced: 2.5.0
    - fixed: 2.5.2
    - introduced: 2.6.0
    - fixed: 2.6.1
    - introduced: "2.7.0rc0"
    - fixed: 2.7.0
references:
- type: REPORT
  url: https://github.com/tensorflow/tensorflow/issues/46909
- type: ADVISORY
  url: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-gh8h-7j2j-qv4f
- type: FIX
  url: https://github.com/tensorflow/tensorflow/commit/874bda09e6702cd50bac90b453b50bcc65b2769e
aliases:
- CVE-2021-41200
- GHSA-gh8h-7j2j-qv4f
modified: "2021-11-09T17:40:00Z"
published: "2021-11-05T20:15:00Z"
