id: PYSEC-0000-CVE-2021-37655
package:
  name: tensorflow
  ecosystem: PyPI
details: 'TensorFlow is an end-to-end open source platform for machine learning. In
  affected versions an attacker can trigger a read from outside of bounds of heap
  allocated data by sending invalid arguments to `tf.raw_ops.ResourceScatterUpdate`.
  The [implementation](https://github.com/tensorflow/tensorflow/blob/f24faa153ad31a4b51578f8181d3aaab77a1ddeb/tensorflow/core/kernels/resource_variable_ops.cc#L919-L923)
  has an incomplete validation of the relationship between the shapes of `indices`
  and `updates`: instead of checking that the shape of `indices` is a prefix of the
  shape of `updates` (so that broadcasting can happen), code only checks that the
  number of elements in these two tensors are in a divisibility relationship. We have
  patched the issue in GitHub commit 01cff3f986259d661103412a20745928c727326f. The
  fix will be included in TensorFlow 2.6.0. We will also cherrypick this commit on
  TensorFlow 2.5.1, TensorFlow 2.4.3, and TensorFlow 2.3.4, as these are also affected
  and still in supported range.'
affects:
  ranges:
  - type: GIT
    repo: https://github.com/tensorflow/tensorflow
    fixed: 01cff3f986259d661103412a20745928c727326f
  - type: ECOSYSTEM
    introduced: 2.3.0
    fixed: 2.3.4
  - type: ECOSYSTEM
    introduced: 2.4.0
    fixed: 2.4.3
references:
- type: WEB
  url: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-7fvx-3jfc-2cpc
- type: WEB
  url: https://github.com/tensorflow/tensorflow/commit/01cff3f986259d661103412a20745928c727326f
aliases:
- CVE-2021-37655
modified: "2021-08-18T14:27:00Z"
published: "2021-08-12T21:15:00Z"
